// Generated by scripts/generate-types.mjs. Edit scripts/type-templates instead.

import type AlpineComponentLoader from './index.d.ts';

export interface ACLDiagnosticSnapshot {
    schemaVersion: 1;
    generatedAt: string;
    loaderVersion: string | null;
    config: Record<string, unknown>;
    registeredTags: string[];
    dataCache: unknown;
    components: Array<Record<string, unknown>>;
    timeline?: Array<Record<string, unknown>>;
    requestActivity?: Array<Record<string, unknown>>;
    snapshots?: Array<Record<string, unknown>>;
    selected?: Record<string, unknown> | null;
}

export function redactDiagnostics<T = unknown>(value: T, key?: string): unknown;
export function createDiagnosticSnapshot(
    loaderClass: typeof AlpineComponentLoader,
    root?: ParentNode | null
): ACLDiagnosticSnapshot;
export function createComponentSnapshot(element: HTMLElement): Record<string, unknown>;
export function diffDiagnosticSnapshots(before: unknown, after: unknown): Array<{
    path: string;
    before: unknown;
    after: unknown;
}>;

export default class ACLDebugger {
    static getSnapshot(loaderClass: typeof AlpineComponentLoader): ACLDiagnosticSnapshot;
    static inject(loaderClass: typeof AlpineComponentLoader): void;
}
