// Generated by scripts/generate-types.mjs. Edit scripts/type-templates instead.

import type { ACLRuntimeRecord } from './index.d.ts';

export interface ACLExporter extends Function {
    (record: ACLRuntimeRecord): void;
    flush?(): Promise<void> | void;
    dispose?(): Promise<void> | void;
    readonly size?: number;
}

export interface ACLBatchExporterOptions {
    send(records: ACLRuntimeRecord[]): void | Promise<void>;
    batchSize?: number;
    flushInterval?: number;
    maxQueue?: number;
    retries?: number;
    retryDelay?: number;
    target?: EventTarget;
}

export function createBatchExporter(options: ACLBatchExporterOptions): ACLExporter;
export function createBeaconExporter(
    options: Omit<ACLBatchExporterOptions, 'send'> & {
        url: string | URL;
        fetch?: typeof fetch;
        navigator?: Navigator;
        headers?: Record<string, string>;
    },
): ACLExporter;
export function createOpenTelemetryExporter(options?: {
    tracer?: unknown;
    meter?: unknown;
    logger?: unknown;
    maxSpans?: number;
}): ACLExporter;
export function createSentryExporter(options: { client: unknown }): ACLExporter;
export function connectExporter(
    loader: { subscribe(listener: (record: ACLRuntimeRecord) => void): () => void },
    exporter: ACLExporter,
): {
    flush(): Promise<void> | void;
    dispose(): Promise<void>;
};

declare const exporters: {
    connectExporter: typeof connectExporter;
    createBatchExporter: typeof createBatchExporter;
    createBeaconExporter: typeof createBeaconExporter;
    createOpenTelemetryExporter: typeof createOpenTelemetryExporter;
    createSentryExporter: typeof createSentryExporter;
};
export default exporters;
