// Generated by scripts/generate-types.mjs. Edit scripts/type-templates instead.

export type ACLInferenceMode = 'safe' | 'report' | 'off';
export type ACLWatchTask = 'manifest' | 'types' | 'schema' | 'routes' | 'offline' | 'skeleton' | 'audit';

export interface ACLRouteConfigEntry {
    key?: string;
    id?: string;
    path: string;
    components?: string[];
    groups?: string[];
    discover?: boolean;
}

export interface ACLProjectConfig {
    root?: string;
    components?: {
        directory: string;
        manifest: string;
        inference?: ACLInferenceMode;
        update?: boolean;
        prune?: boolean;
    };
    routes?: {
        manifest?: string;
        outDir: string;
        target?: string;
        timeout?: number;
        browserType?: 'chromium' | 'firefox' | 'webkit';
        entries: ACLRouteConfigEntry[];
    };
    contracts?: {
        types?: string;
        customElements?: string;
        manifestSchema?: string;
        componentSchema?: string;
        offlineSchema?: string;
    };
    offline?: {
        manifest?: string;
        outDir?: string;
        groups?: string[];
        assets?: string[];
        baseUrl?: string;
        namespace?: string;
        config?: string;
        minifyJavaScriptAssets?: boolean;
    };
    watch?: {
        tasks?: ACLWatchTask[];
        debounce?: number;
        pollInterval?: number;
    };
    audit?: {
        routes?: string[];
        root?: string;
        index?: string;
        format?: 'console' | 'json' | 'junit' | 'sarif';
        out?: string;
        outFile?: string;
        axe?: boolean;
        timeout?: number;
        browserType?: 'chromium' | 'firefox' | 'webkit';
        baseline?: string;
        suppressions?: string;
        updateBaseline?: boolean;
    };
    vite?: {
        moduleDelivery?: 'copy' | 'external';
        moduleDirectory?: string;
        moduleBase?: string;
        routeDirectory?: string;
        generate?: boolean;
    };
    skeleton?: {
        root?: string;
        target?: string;
        outDir?: string;
        routes?: string[];
        include?: string[];
        exclude?: string[];
        timeout?: number;
        breakpoint?: number;
        mode?: 'css' | 'manifest' | 'both';
        allowPartial?: boolean;
        force?: boolean;
    };
}

export function defineConfig<T extends ACLProjectConfig>(config: T): T;
export function loadProjectConfig(options?: {
    configFile?: string | null;
    invocationDirectory?: string;
    optional?: boolean;
    overrides?: Partial<ACLProjectConfig>;
}): Promise<{
    config: ACLProjectConfig & { root: string };
    configFile: string | null;
    configDirectory: string;
}>;

export default defineConfig;
