import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve declaration template paths and the generated file banner
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..'),
    templateRoot = join(projectRoot, 'scripts', 'type-templates'),
    outputRoot = join(projectRoot, 'types'),
    banner = '// Generated by scripts/generate-types.mjs. Edit scripts/type-templates instead.\n\n';

await mkdir(outputRoot, { recursive: true });
// Copy declaration templates into the publishable type directory
for (const entry of await readdir(templateRoot, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.d.ts')) continue;
    const source = await readFile(join(templateRoot, entry.name), 'utf8');
    await writeFile(join(outputRoot, entry.name), `${banner}${source}`);
}

process.stdout.write('Generated public TypeScript declarations.\n');
