import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';
import {
    createStagedPackageImports,
    normalizeExampleNames,
    stageExample,
    stageExamples,
    updateStagedBaseHref,
    updateStagedImportMap,
    updateStagedSkeletonStylesheet,
    validateExampleName,
} from '../../scripts/stage-example.mjs';

const repositoryRoot = resolve('.'),
    alpineUrl = 'https://cdn.jsdelivr.net/npm/alpinejs@3.15.12/dist/cdn.min.js',
    staticExamples = ['a11y', 'feature-lab', 'offline', 'playground'];

const createSkeletonDependencies = (calls = []) => ({
    async generateSkeletons(options, dependencies) {
        // Materialize deterministic generated output without launching a browser in unit tests
        const name = basename(dirname(options.outDir)),
            path = resolve(options.outDir, 'acl-skeletons.css'),
            component = `${name}-stage-component`;
        calls.push({
            dependencies,
            options,
        });
        await mkdir(options.outDir, { recursive: true });
        await writeFile(
            path,
            `/* Generated by alpine-component-loader skeleton. Do not edit. */\n${component}:not(:defined){display:block}\n`,
        );
        return {
            components: [component],
            failures: [],
            files: [path],
            mode: 'css',
            warnings: [],
        };
    },
    // Keep unit output quiet while retaining progress callback coverage
    onProgress() {},
});

const readImportMap = (source) => {
    // Decode the single import map from staged HTML
    const match = source.match(/<script\b[^>]*type=["']importmap["'][^>]*>([\s\S]*?)<\/script\s*>/i);
    if (!match) throw new TypeError('Import map not found.');
    return JSON.parse(match[1]);
};

const collectFiles = async (root, directory = root) => {
    // Collect deterministic content identities below one artifact root
    const files = [];
    // Visit every staged file in path order
    for (const entry of (await readdir(directory, { withFileTypes: true })).sort(
        // Compare staged paths in deterministic order
        (left, right) => left.name.localeCompare(right.name),
    )) {
        const path = join(directory, entry.name);
        if (entry.isDirectory()) files.push(...(await collectFiles(root, path)));
        else if (entry.isFile())
            files.push({
                path: relative(root, path),
                digest: createHash('sha256')
                    .update(await readFile(path))
                    .digest('hex'),
            });
    }
    return files;
};

test('staged package imports follow every browser distribution export', async () => {
    // Compare generated mappings with package distribution exports
    const imports = await createStagedPackageImports(),
        packageJson = JSON.parse(await readFile(resolve('package.json'), 'utf8')),
        expected = Object.fromEntries(
            Object.entries(packageJson.exports)
                .filter(
                    // Select exports backed by browser distribution files
                    ([, definition]) => definition?.import?.startsWith('./dist/'),
                )
                .map(
                    // Convert one package export to its public staged identity
                    ([subpath, definition]) => [
                        subpath === '.' ? packageJson.name : `${packageJson.name}${subpath.slice(1)}`,
                        `/${definition.import.slice(2).replace(/\.js$/, '.min.js')}`,
                    ],
                ),
        );
    assert.deepEqual(imports, expected);
});

test('staged import maps preserve application mappings and scopes', async () => {
    // Rewrite an application-owned import map
    const packageImports = await createStagedPackageImports(),
        source = `<!doctype html><html><head>
        <script type="importmap">{
            "imports": {
                "application": "/application.js",
                "alpine-component-loader": "/__acl_hmr/modules/index.min.js",
                "alpine-component-loader/old": "/old.js"
            },
            "scopes": { "/admin/": { "application": "/admin.js" } }
        }</script></head><body></body></html>`,
        transformed = updateStagedImportMap(source, packageImports),
        importMap = readImportMap(transformed);
    assert.equal(importMap.imports.application, '/application.js');
    assert.equal(importMap.imports['alpine-component-loader'], '/dist/index.min.js');
    assert.equal(importMap.imports['alpine-component-loader/old'], undefined);
    assert.deepEqual(importMap.scopes, { '/admin/': { application: '/admin.js' } });
    assert.deepEqual(
        Object.fromEntries(
            Object.entries(importMap.imports).filter(
                // Select the staged ACL package family
                ([specifier]) =>
                    specifier === 'alpine-component-loader' || specifier.startsWith('alpine-component-loader/'),
            ),
        ),
        packageImports,
    );
});

test('staged import maps are inserted and malformed or ambiguous maps fail', async () => {
    // Exercise insertion and invalid authored map diagnostics
    const packageImports = await createStagedPackageImports(),
        inserted = updateStagedImportMap(
            '<!doctype html><html><head><title>Example</title></head></html>',
            packageImports,
        );
    assert.deepEqual(readImportMap(inserted).imports, packageImports);
    assert.throws(
        // Reject malformed authored JSON
        () =>
            updateStagedImportMap('<html><head><script type="importmap">{bad}</script></head></html>', packageImports),
        /malformed/,
    );
    assert.throws(
        // Reject ambiguous multiple import maps
        () =>
            updateStagedImportMap(
                '<html><head><script type="importmap">{}</script><script type="importmap">{}</script></head></html>',
                packageImports,
            ),
        /more than one/,
    );
});

test('staged document bases remain nested across clean and index URL navigation', () => {
    // Insert and replace canonical nested bases without reserializing the page
    const source = '<!doctype html><html><head><title>Example</title></head><body></body></html>',
        inserted = updateStagedBaseHref(source, 'feature-lab'),
        existing = updateStagedBaseHref(
            '<!doctype html><html><head><base target="_self" href="../"><title>Example</title></head></html>',
            'a11y',
        ),
        missingHref = updateStagedBaseHref(
            '<!doctype html><html><head><base target="_self"><title>Example</title></head></html>',
            'offline',
        );
    assert.match(inserted, /<base href="\/examples\/feature-lab\/index\.html" data-acl-stage-base>/);
    assert.match(existing, /<base target="_self" href="\/examples\/a11y\/index\.html">/);
    assert.match(missingHref, /<base target="_self" href="\/examples\/offline\/index\.html">/);
    const base = 'https://static.example.test/examples/feature-lab/index.html';
    assert.equal(new URL('./styles.css', base).pathname, '/examples/feature-lab/styles.css');
    assert.equal(
        new URL('./components/shadow-card.html', base).pathname,
        '/examples/feature-lab/components/shadow-card.html',
    );
    assert.throws(
        // Reject ambiguous base URL ownership
        () =>
            updateStagedBaseHref(
                '<!doctype html><html><head><base href="/one/"><base href="/two/"></head></html>',
                'playground',
            ),
        /more than one base/,
    );
    assert.throws(
        // Reject documents that cannot safely receive the generated base
        () => updateStagedBaseHref('<!doctype html><html><body></body></html>', 'playground'),
        /explicit head/,
    );
});

test('staged skeleton stylesheets follow authored styles and remain idempotent', () => {
    // Insert one stage-owned stylesheet without reserializing unrelated head content
    const source =
            '<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet preload" href="./styles.css"><script type="module" src="./app.js"></script></head></html>',
        transformed = updateStagedSkeletonStylesheet(source),
        repeated = updateStagedSkeletonStylesheet(transformed);
    assert.equal(repeated, transformed);
    assert.match(
        transformed,
        /styles\.css">\s*<link rel="stylesheet" href="\.\/skeletons\/acl-skeletons\.css" data-acl-stage-skeletons><script/s,
    );
    assert.throws(
        // Reject a document that cannot safely receive the generated stylesheet
        () => updateStagedSkeletonStylesheet('<!doctype html><html><body></body></html>'),
        /explicit head/,
    );
    assert.throws(
        // Reject ambiguous stage-owned stylesheet markup
        () =>
            updateStagedSkeletonStylesheet(
                '<html><head><link data-acl-stage-skeletons><link data-acl-stage-skeletons></head></html>',
            ),
        /more than one staged skeleton/,
    );
});

test('stage selection accepts static examples and rejects backend or unsafe targets', () => {
    // Exercise the complete selector allowlist
    staticExamples.forEach(
        // Accept every documented static example
        (name) => assert.equal(validateExampleName(name), name),
    );
    assert.equal(validateExampleName(), 'playground');
    assert.throws(
        // Reject the development-server example
        () => validateExampleName('hmr'),
        /development HMR server/,
    );
    assert.throws(
        // Reject the focused SSR example
        () => validateExampleName('ssr'),
        /SSR server/,
    );
    assert.throws(
        // Reject the SSR feature lab
        () => validateExampleName('feature-lab-ssr'),
        /SSR server/,
    );
    assert.throws(
        // Reject traversal disguised as a selector
        () => validateExampleName('../playground'),
        /Unknown static example/,
    );
    assert.throws(
        // Reject an explicit empty selector
        () => validateExampleName(''),
        /Unknown static example/,
    );
});

test('stage selections default, deduplicate, and retain first command-line order', () => {
    // Normalize empty, repeated, and reordered selector lists
    assert.deepEqual(normalizeExampleNames(), ['playground']);
    assert.deepEqual(normalizeExampleNames([]), ['playground']);
    assert.deepEqual(normalizeExampleNames(['offline', 'a11y', 'offline', 'playground', 'a11y']), [
        'offline',
        'a11y',
        'playground',
    ]);
    assert.deepEqual(normalizeExampleNames(['playground', 'feature-lab']), ['playground', 'feature-lab']);
    assert.deepEqual(normalizeExampleNames(['feature-lab', 'playground']), ['feature-lab', 'playground']);
    assert.throws(
        // Reject an invalid selection even when its neighbors are valid
        () => normalizeExampleNames(['a11y', '../offline', 'playground']),
        /Unknown static example/,
    );
    assert.throws(
        // Reject backend-dependent examples in a mixed list
        () => normalizeExampleNames(['offline', 'hmr']),
        /development HMR server/,
    );
    assert.throws(
        // Reject non-list internal input
        () => normalizeExampleNames('playground'),
        /must be an array/,
    );
});

test('every static source selects the exact pinned Alpine CDN runtime', async () => {
    // Verify authored pages and iframe startup use one CDN identity
    // Inspect every backend-free page
    for (const name of staticExamples) {
        const source = await readFile(resolve('examples', name, 'index.html'), 'utf8'),
            expected = `<script defer src="${alpineUrl}"></script>`;
        assert.equal(source.split(expected).length - 1, 1, `${name} must select the pinned Alpine CDN once`);
    }
    const playground = await readFile(resolve('examples/playground/playground.js'), 'utf8');
    assert.match(playground, new RegExp(`alpineUrl = '${alpineUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}'`));
    assert.doesNotMatch(playground, /node_modules\/alpinejs/);
});

test('each supported example produces a direct-import-map static artifact', async (context) => {
    // Stage and inspect every supported example
    const temporaryRoot = await mkdtemp(join(tmpdir(), 'acl-stage-examples-'));
    context.after(async () => {
        // Release generated test artifacts
        await rm(temporaryRoot, {
            recursive: true,
            force: true,
        });
    });

    const calls = [],
        dependencies = createSkeletonDependencies(calls);
    // Verify each artifact through physical output files
    for (const name of staticExamples) {
        const outputRoot = resolve(temporaryRoot, name),
            result =
                name === 'a11y'
                    ? await stageExamples(
                          {
                              names: [name, name],
                              root: repositoryRoot,
                              outputRoot,
                          },
                          dependencies,
                      )
                    : await stageExample(
                          {
                              name,
                              root: repositoryRoot,
                              outputRoot,
                          },
                          dependencies,
                      );
        assert.deepEqual(result.examples, [name]);
        assert.equal(result.mode, 'redirect');
        const entry = await readFile(resolve(outputRoot, 'examples', name, 'index.html'), 'utf8'),
            importMap = readImportMap(entry);
        assert.match(entry, new RegExp(`<base href="/examples/${name}/index\\.html" data-acl-stage-base>`));
        assert.equal(importMap.imports['alpine-component-loader'], '/dist/index.min.js');
        assert.equal(importMap.imports['alpine-component-loader/testing/vitest'], '/dist/testing-vitest.min.js');
        assert.match(
            await readFile(resolve(outputRoot, 'index.html'), 'utf8'),
            new RegExp(`examples/${name}/index.html`),
        );
        assert.equal((await stat(resolve(outputRoot, 'dist/index.min.js'))).isFile(), true);
        assert.equal((await stat(resolve(outputRoot, 'examples', name, 'skeletons/acl-skeletons.css'))).isFile(), true);
        await assert.rejects(stat(resolve(outputRoot, 'node_modules')), /ENOENT/);
        await assert.rejects(stat(resolve(outputRoot, 'styles.css')), /ENOENT/);
        assert.doesNotMatch(entry, /\/__acl_hmr\/modules\//);
        assert.match(
            entry,
            /<link rel="stylesheet" href="\.\/skeletons\/acl-skeletons\.css" data-acl-stage-skeletons>/,
        );
    }
    assert.equal(calls.length, staticExamples.length);
    calls.forEach(({ dependencies: captureDependencies, options }) => {
        // Verify one normalized capture contract
        const name = basename(dirname(options.outDir));
        assert.equal(options.target.type, 'local');
        assert.equal(options.target.root.startsWith(temporaryRoot), true);
        assert.equal(options.target.index, join('examples', name, 'index.html'));
        assert.equal(options.mode, 'css');
        assert.equal(options.allowPartial, false);
        assert.equal(options.force, true);
        assert.deepEqual(options.viewports, {
            mobile: {
                width: 390,
                height: 844,
            },
            desktop: {
                width: 1440,
                height: 900,
            },
        });
        assert.equal(typeof captureDependencies.preparePage, 'function');
    });

    const offlineRoot = resolve(temporaryRoot, 'offline'),
        offlineManifest = JSON.parse(
            await readFile(resolve(offlineRoot, 'examples/offline/acl-precache-manifest.json'), 'utf8'),
        );
    assert.equal((await stat(resolve(offlineRoot, 'examples/offline/app.min.js'))).isFile(), true);
    assert.ok(
        offlineManifest.entries.some(
            // Require the exact remote Alpine runtime to be available after a successful install
            (entry) => entry.url === alpineUrl && entry.required === false,
        ),
    );
    assert.ok(
        offlineManifest.entries.some(
            // Precache the staged skeleton stylesheet for a complete offline reload
            (entry) => entry.url === '/examples/offline/skeletons/acl-skeletons.css' && entry.required === true,
        ),
    );
});

test('multiple examples produce an ordered Feature Lab styled catalog and one shared runtime', async (context) => {
    // Stage a mixed selection with Offline generation and a duplicate
    const temporaryRoot = await mkdtemp(join(tmpdir(), 'acl-stage-catalog-')),
        outputRoot = resolve(temporaryRoot, 'site');
    context.after(async () => {
        // Release generated catalog artifacts
        await rm(temporaryRoot, {
            recursive: true,
            force: true,
        });
    });

    const result = await stageExamples(
        {
            names: ['offline', 'a11y', 'playground', 'a11y'],
            root: repositoryRoot,
            outputRoot,
        },
        createSkeletonDependencies(),
    );
    assert.deepEqual(result.examples, ['offline', 'a11y', 'playground']);
    assert.equal(result.mode, 'catalog');
    assert.equal(result.outputRoot, outputRoot);

    const catalog = await readFile(resolve(outputRoot, 'index.html'), 'utf8'),
        styles = await readFile(resolve(outputRoot, 'styles.css'), 'utf8'),
        packageJson = JSON.parse(await readFile(resolve('package.json'), 'utf8')),
        packageImports = await createStagedPackageImports(),
        orderedNames = [...catalog.matchAll(/data-example="([^"]+)"/g)].map(
            // Read the generated card identity in document order
            (match) => match[1],
        );
    assert.deepEqual(orderedNames, ['offline', 'a11y', 'playground']);
    assert.doesNotMatch(catalog, /http-equiv="refresh"/);
    assert.doesNotMatch(catalog, /<script\b/i);
    assert.doesNotMatch(catalog, /<link\b[^>]*rel="stylesheet"/i);
    const embeddedStyles = catalog.match(/<style data-acl-stage-catalog>\s*([\s\S]*?)\s*<\/style>/)?.[1];
    assert.equal(embeddedStyles, styles.trim());
    assert.match(catalog, /AlpineComponentLoader/);
    assert.match(catalog, /A lightweight, build-free component loader for/);
    assert.match(catalog, /class="github-link"[^>]*>View on GitHub<\/a>/);
    assert.match(catalog, /Explore ACL in the browser/);
    assert.match(catalog, /<dd>3<\/dd>/);
    assert.match(catalog, new RegExp(`<dd>v${packageJson.version.replaceAll('.', '\\.')}<\\/dd>`));
    assert.match(catalog, /<dd>Static<\/dd>/);
    assert.match(catalog, /Offline Application/);
    assert.match(catalog, /Accessibility Auditing/);
    assert.match(catalog, /ACL Playground/);
    assert.match(catalog, /Test a generated precache graph, navigation fallback, runtime caching/);
    assert.match(catalog, /Run component audits, inspect scanner results/);
    assert.match(catalog, /Edit a complete ACL dashboard with incremental HMR/);
    assert.match(catalog, /LTDev LLC · MIT License/);
    assert.match(catalog, /alpine-component-loader\/issues/);
    assert.match(catalog, /href="https:\/\/alpinejs\.dev\/"[^>]*>Alpine\.js<\/a>/);
    assert.match(catalog, /href="#top">Back to top/);
    assert.match(styles, /\.example-grid\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/);
    assert.match(styles, /\.example-card\s*\{[\s\S]*align-items:\s*center;/);
    // Verify every selected card exposes its application and bundled guide
    for (const name of ['offline', 'a11y', 'playground']) {
        assert.match(catalog, new RegExp(`href="./examples/${name}/index\\.html">Open example`));
        assert.match(catalog, new RegExp(`href="./examples/${name}/README\\.md">Read guide`));
        const entry = await readFile(resolve(outputRoot, 'examples', name, 'index.html'), 'utf8');
        assert.equal((await stat(resolve(outputRoot, 'examples', name, 'README.md'))).isFile(), true);
        assert.equal(readImportMap(entry).imports['alpine-component-loader'], '/dist/index.min.js');
        assert.doesNotMatch(entry, /\/__acl_hmr\/modules\//);
        assert.match(entry, /data-acl-stage-skeletons/);
        assert.equal((await stat(resolve(outputRoot, 'examples', name, 'skeletons/acl-skeletons.css'))).isFile(), true);
    }
    await assert.rejects(stat(resolve(outputRoot, 'examples/feature-lab')), /ENOENT/);
    assert.equal((await stat(resolve(outputRoot, 'dist/index.min.js'))).isFile(), true);
    assert.equal((await stat(resolve(outputRoot, 'examples/offline/app.min.js'))).isFile(), true);
    // Require every mapped browser export to exist in the one shared distribution
    for (const target of Object.values(packageImports)) {
        assert.equal((await stat(resolve(outputRoot, target.replace(/^\/+/, '')))).isFile(), true);
    }
    const offlineManifest = JSON.parse(
        await readFile(resolve(outputRoot, 'examples/offline/acl-precache-manifest.json'), 'utf8'),
    );
    assert.equal(offlineManifest.config.navigation.fallback, '/examples/offline/index.html');
    assert.deepEqual(offlineManifest.config.navigation.allow, ['/examples/offline/']);
    assert.ok(
        offlineManifest.entries.some(
            // Retain the route-scoped Offline application entry in a shared artifact
            (entry) => entry.url === '/examples/offline/app.min.js' && entry.required === true,
        ),
    );
    assert.ok(
        offlineManifest.entries.some(
            // Retain the generated loading UI in the Offline application shell
            (entry) => entry.url === '/examples/offline/skeletons/acl-skeletons.css',
        ),
    );
    assert.match(styles, /--primary: #1d4ed8/);
    assert.match(styles, /1180px/);
    assert.match(styles, /border-radius: 12px/);
    assert.match(styles, /@media \(max-width: 760px\)/);
    assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
    assert.match(styles, /:focus-visible/);
});

test('staging is reproducible and preserves existing output after a failure', async (context) => {
    // Compare repeated output and protect a prior artifact
    const temporaryRoot = await mkdtemp(join(tmpdir(), 'acl-stage-atomic-')),
        first = resolve(temporaryRoot, 'first'),
        second = resolve(temporaryRoot, 'second'),
        brokenRoot = resolve(temporaryRoot, 'broken'),
        protectedOutput = resolve(temporaryRoot, 'protected');
    context.after(async () => {
        // Release generated test artifacts
        await rm(temporaryRoot, {
            recursive: true,
            force: true,
        });
    });

    await stageExamples(
        {
            names: ['offline', 'playground', 'offline', 'a11y'],
            root: repositoryRoot,
            outputRoot: first,
        },
        createSkeletonDependencies(),
    );
    await stageExamples(
        {
            names: ['offline', 'playground', 'a11y'],
            root: repositoryRoot,
            outputRoot: second,
        },
        createSkeletonDependencies(),
    );
    assert.deepEqual(await collectFiles(first), await collectFiles(second));

    await mkdir(resolve(brokenRoot, 'examples/playground'), { recursive: true });
    await writeFile(
        resolve(brokenRoot, 'examples/playground/index.html'),
        `<!doctype html><html><head><script defer src="${alpineUrl}"></script></head></html>`,
    );
    await mkdir(protectedOutput);
    await writeFile(resolve(protectedOutput, 'marker.txt'), 'keep');
    await assert.rejects(
        stageExamples(
            {
                names: ['playground', 'ssr', 'a11y'],
                root: repositoryRoot,
                outputRoot: protectedOutput,
            },
            createSkeletonDependencies(),
        ),
        /SSR server/,
    );
    assert.equal(await readFile(resolve(protectedOutput, 'marker.txt'), 'utf8'), 'keep');
    await assert.rejects(
        stageExample(
            {
                name: 'playground',
                root: brokenRoot,
                outputRoot: protectedOutput,
            },
            createSkeletonDependencies(),
        ),
        /distribution is missing/,
    );
    assert.equal(await readFile(resolve(protectedOutput, 'marker.txt'), 'utf8'), 'keep');
    await assert.rejects(
        stageExamples(
            {
                names: ['playground'],
                root: repositoryRoot,
                outputRoot: protectedOutput,
            },
            {
                async generateSkeletons() {
                    // Simulate a browser-backed capture failure after temporary staging begins
                    throw new Error('capture failed');
                },
                // Suppress expected failure-test progress
                onProgress() {},
            },
        ),
        /capture failed/,
    );
    assert.equal(await readFile(resolve(protectedOutput, 'marker.txt'), 'utf8'), 'keep');
});
